In [1]:
import numpy as np

In [5]:
data1 = [6,7.5,8,0,1]
data1

[6, 7.5, 8, 0, 1]

In [6]:
# numpy를 이용하여 1차원 1배열로 변형하기
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
# 배열의 크기 확인하기
arr1.shape

(5,)

### 2차원

In [9]:
data2 = [
    [1,2,3,4],
    [5,6,7,8]
]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [10]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.shape

(2, 4)

In [12]:
# 0으로 구성된 1차원 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
# 0으로 구성된 5행 2열의 3차원 배열 생성
np.zeros([3, 5, 2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [14]:
# 1로만 구성된 배열 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
# 10으로 구성된 배열 생성
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [16]:
# 0으로 구성된 3행 5열 배열 생성
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [18]:
# 범위가 있는 배열
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [19]:
# 정수형으로 이루어진 배열 -> 실수형으로 변환
arr = np.array([1,2,3,4,5], dtype=np.int64)
arr

array([1, 2, 3, 4, 5])

In [20]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [22]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr2 = np.array([
    [7,8,9],
    [10,11,12]
])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [24]:
arr1 + arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [25]:
arr1 - arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [26]:
arr1 * arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [27]:
arr1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [28]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [29]:
1 / arr1 # 역수

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [30]:
(1 / arr1) * arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
arr[5:9] = 12
arr

array([1, 2, 3, 4, 5])

### 2차원 배열

In [33]:
arr2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

In [48]:
# 2번 행의 자료 출력
arr2d[2,:]

array([ 9, 10, 11, 12])

In [49]:
# 1에서 2번행의 자료 출력
arr2d[1:3,]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
# 3번 열의 자료 출력
arr2d[:,3]

array([ 4,  8, 12, 16])

In [44]:
# 0,1열의 자료 출력
arr2d[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [51]:
# 1행 2열의 자료 출력
arr2d[1,2]

7

In [62]:
arr2d[0:2,1:3] = 0
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 난수발생
- rand : 0~1사이의 균일 분포
- randn : 가우시안 표준 정규 분포
- randint : 균일분포의 정수 난수

In [71]:
names = np.array([
    "Charles",
    "Kenny",
    "Hayoung",
    "Charles",
    "Hayoung",
    "Kenny",
    "Kenny"
    ])

data = np.random.randn(7,4)

In [64]:
data

array([[ 0.02537012, -0.47202748,  0.14999896,  0.5482748 ],
       [-0.68386769, -1.46121645, -1.87795942,  1.49352531],
       [ 0.91845353,  0.0248806 ,  1.15777056,  0.73030513],
       [ 0.29686055,  0.19665443, -0.72205396,  0.27337   ],
       [ 0.85503786, -0.54309794,  1.57152099,  0.12346115],
       [ 0.67935532,  0.48484776,  2.41706893, -0.27887796],
       [-0.3267853 ,  0.63261678, -0.07408599,  0.9860859 ]])

In [72]:
names == 'Charles'

array([ True, False, False,  True, False, False, False])

In [76]:
data[names == 'Charles',:]

array([[ 0.84851958,  1.14141956, -0.79368961,  0.45990717],
       [ 1.62055487, -0.73076869, -0.65904782,  1.36052824]])

In [75]:
data[data[:,3] < 0, :] = 0
data

array([[ 0.84851958,  1.14141956, -0.79368961,  0.45990717],
       [ 0.065868  , -0.1559412 ,  0.49377434,  0.81028536],
       [-1.6541971 , -0.62609935,  1.04680361,  0.24226339],
       [ 1.62055487, -0.73076869, -0.65904782,  1.36052824],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.2391785 ,  0.83661516,  0.22625672,  0.19971302],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [78]:
# 정렬
arr = np.random.rand(8)
arr

array([0.59210011, 0.01082793, 0.65849338, 0.22082079, 0.5418399 ,
       0.83224598, 0.95324009, 0.99938585])

In [82]:
np.sort(arr)[::-1] # 내림차순

array([0.99938585, 0.95324009, 0.83224598, 0.65849338, 0.59210011,
       0.5418399 , 0.22082079, 0.01082793])

In [81]:
np.sort(arr) # 오름차순

array([0.01082793, 0.22082079, 0.5418399 , 0.59210011, 0.65849338,
       0.83224598, 0.95324009, 0.99938585])

In [83]:
arr = np.random.rand(5,3)
arr

array([[0.4649507 , 0.79479205, 0.82814727],
       [0.0279821 , 0.34564906, 0.05799357],
       [0.0865178 , 0.86579175, 0.31524859],
       [0.31082229, 0.95488614, 0.50330185],
       [0.90970322, 0.51109633, 0.64661971]])

In [84]:
np.sort(arr, axis=0) # 열방향 오름 차순

array([[0.0279821 , 0.34564906, 0.05799357],
       [0.0865178 , 0.51109633, 0.31524859],
       [0.31082229, 0.79479205, 0.50330185],
       [0.4649507 , 0.86579175, 0.64661971],
       [0.90970322, 0.95488614, 0.82814727]])

In [85]:
np.sort(arr, axis=1) # 행방향 오름 차순

array([[0.4649507 , 0.79479205, 0.82814727],
       [0.0279821 , 0.05799357, 0.34564906],
       [0.0865178 , 0.31524859, 0.86579175],
       [0.31082229, 0.50330185, 0.95488614],
       [0.51109633, 0.64661971, 0.90970322]])

---
# reshape

In [86]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [87]:
# 2차원 배열로 변경
arr1 = np.reshape(arr, (2, 4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
# 3차원 배열로 변경
arr2 = np.reshape(arr, (2,2,2))
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [91]:
# 2차원 배열을 1차원으로 변경
arr3 = arr1.reshape(-1)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
arr4 = arr1.reshape(-1,1)
arr4

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [94]:
arr3 == arr4

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

In [95]:
# 3차원 배열을 1차원으로 변경
arr5 = arr2.reshape(-1,1)
arr5

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [96]:
arr3 == arr5

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])